UPC-75 Archived versions should not be visible in the compatibility m…
SonarSource/sonar-update-center pull request #75
Opened 2022-04-13 15:11 UTC by zipeng-wu-sonarsource

2022-04-13 16:11 UTC, pierre-guillot-sonarsource commented
I discussed the implementation with Zipeng, and I think we can go further and actually remove the "Bundled" concept. I created [UPC-124](https://jira.sonarsource.com/browse/UPC-124) to track this effort, and open a PR https://github.com/SonarSource/sonar-update-center/pull/76 with the implementation, that actually allows us to simplify @zipeng-wu-sonarsource implementation on `matrix-template.html.ftl`

2022-04-14 08:38 UTC, aurelien-poscia-sonarsource requested changes

2022-04-14 08:38 UTC, aurelien-poscia-sonarsource commented on sonar-update-center-mojo/src/main/java/org/sonar/updatecenter/mojo/CompatibilityMatrix.java
> +          matrixPlugin.getCompatibleVersionBySqVersion().put(sq.getVersion().toString(), lastCompatible.isArchived() ? "" : lastCompatible.getVersion().toString());
why to add at all the version in case it is archived?

2022-04-14 08:38 UTC, aurelien-poscia-sonarsource commented on sonar-update-center-mojo/src/main/java/org/sonar/updatecenter/mojo/CompatibilityMatrix.java
> +    }
This checks is a bit difficult to read: we rely on the fact that the map contains an empty string for a given version to deduct that it is archived.

2022-04-14 10:37 UTC, closed without merging